# Generated by Django 4.2.4 on 2023-09-20 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_me_text'),
        ('resumes', '0008_alter_skill_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='resumes.coursecategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_on',
            field=models.IntegerField(blank=True, choices=[(0, 'running'), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030)], null=True, verbose_name='End On'),
        ),
        migrations.AlterField(
            model_name='course',
            name='source',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_on',
            field=models.IntegerField(choices=[(0, 'soon'), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030)], verbose_name='Start On'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated On'),
        ),
        migrations.AlterField(
            model_name='course',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='home.me', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated On'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='resumes.skillscategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated On'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='home.me', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='skillscategory',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='skillscategory',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='skillscategory',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='skillscategory',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated On'),
        ),
    ]
