# Generated by Django 4.2.4 on 2023-09-20 16:50

import ckeditor.fields
from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0009_alter_course_body_alter_course_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('title', 'source', 'body'), required_languages=(), virtual_fields=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('title', 'body'), required_languages=(), virtual_fields=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='skillscategory',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Text'),
        ),
    ]
