# Generated by Django 4.2.4 on 2023-09-20 17:27

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0010_course_i18n_skill_i18n_alter_course_body_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='course',
            index=django.contrib.postgres.indexes.GinIndex(fields=['i18n'], name='resumes_cou_i18n_fc18ab_gin'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=django.contrib.postgres.indexes.GinIndex(fields=['i18n'], name='resumes_ski_i18n_58fbf0_gin'),
        ),
    ]
