# Generated by Django 4.2.4 on 2023-09-20 17:49

import django.contrib.postgres.indexes
from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0011_course_resumes_cou_i18n_fc18ab_gin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('title', 'body'), required_languages=(), virtual_fields=True),
        ),
        migrations.AddField(
            model_name='skillscategory',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('title', 'body'), required_languages=(), virtual_fields=True),
        ),
        migrations.AddIndex(
            model_name='coursecategory',
            index=django.contrib.postgres.indexes.GinIndex(fields=['i18n'], name='resumes_cou_i18n_665734_gin'),
        ),
        migrations.AddIndex(
            model_name='skillscategory',
            index=django.contrib.postgres.indexes.GinIndex(fields=['i18n'], name='resumes_ski_i18n_e6b8b9_gin'),
        ),
    ]
