# Generated by Django 4.2.4 on 2024-06-15 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0012_coursecategory_i18n_skillscategory_i18n_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name': 'Course Category', 'verbose_name_plural': 'Course Categories'},
        ),
    ]
