# Generated by Django 4.2.4 on 2024-06-15 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0013_alter_coursecategory_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SkillsCategory',
            new_name='SkillCategory',
        ),
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'verbose_name': 'Skill Category', 'verbose_name_plural': 'Skill Categories'},
        ),
        migrations.RenameIndex(
            model_name='skillcategory',
            new_name='resumes_ski_i18n_4c27c7_gin',
            old_name='resumes_ski_i18n_e6b8b9_gin',
        ),
    ]
