# Generated by Django 4.2.4 on 2023-09-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cover',
            field=models.ImageField(default=1, upload_to='covers/blogs/%y/%m'),
            preserve_default=False,
        ),
    ]
