# Generated by Django 4.2.4 on 2023-09-20 16:12

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('subject', 'title', 'body'), required_languages=(), virtual_fields=True),
        ),
    ]
