# Generated by Django 4.2.4 on 2023-09-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fa', 'Persian')], default='en', max_length=10),
        ),
    ]
