# Generated by Django 4.2.4 on 2023-09-21 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='language',
        ),
    ]
