# Generated by Django 4.2.4 on 2023-09-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_me_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='me',
            name='language',
            field=models.CharField(choices=[('fa', 'persian'), ('en', 'english')], default=2, max_length=2),
            preserve_default=False,
        ),
    ]
