# Generated by Django 4.2.4 on 2023-09-15 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_me_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='me',
            name='language',
        ),
    ]
