# Generated by Django 4.2.4 on 2023-09-20 16:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_me_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='me',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
