# Generated by Django 4.2.4 on 2023-09-20 16:20

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_me_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='me',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name', 'last_name', 'nationality'), required_languages=(), virtual_fields=True),
        ),
    ]
