# Generated by Django 4.2.4 on 2023-09-20 16:22

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_me_i18n'),
    ]

    operations = [
        migrations.AlterField(
            model_name='me',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name', 'last_name', 'nationality', 'summery_text', 'text'), required_languages=(), virtual_fields=True),
        ),
    ]
