# Generated by Django 4.2.4 on 2023-09-20 17:27

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_me_i18n'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='me',
            index=django.contrib.postgres.indexes.GinIndex(fields=['i18n'], name='home_me_i18n_361c89_gin'),
        ),
    ]
