# Generated by Django 4.2.4 on 2023-09-21 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_me_home_me_i18n_361c89_gin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='home.me'),
        ),
    ]
