# Generated by Django 4.2.4 on 2024-06-07 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0012_coursecategory_i18n_skillscategory_i18n_and_more'),
        ('home', '0009_alter_file_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Me',
            new_name='AboutMe',
        ),
        migrations.RenameIndex(
            model_name='aboutme',
            new_name='home_aboutm_i18n_46f9f1_gin',
            old_name='home_me_i18n_361c89_gin',
        ),
    ]
