# Generated by Django 4.2.4 on 2024-06-15 14:16

from django.db import migrations, models
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_me_aboutme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='nationality',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='nationality_city',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name', 'last_name', 'nationality_city', 'summery_text', 'text'), required_languages=(), virtual_fields=True),
        ),
    ]
