# Generated by Django 4.2.4 on 2024-06-15 14:35

from django.db import migrations, models
import django.utils.timezone
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_aboutme_nationality_aboutme_nationality_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutme',
            old_name='summery_text',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='aboutme',
            old_name='text',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='nationality_city',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='nationality',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name', 'last_name', 'nationality', 'bio', 'description'), required_languages=(), virtual_fields=True),
        ),
    ]
