# Generated by Django 4.2.4 on 2024-06-15 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_summery_text_aboutme_bio_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
