# Generated by Django 4.2.4 on 2024-06-15 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_delete_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name_plural': 'About Me'},
        ),
    ]
