# Generated by Django 4.2.4 on 2023-09-02 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgforportfolio',
            name='img',
            field=models.ImageField(upload_to='covers/portfolio/%Y'),
        ),
        migrations.CreateModel(
            name='LinkForPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, db_index=True, max_length=128, unique=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='portfolio.portfolio')),
            ],
        ),
    ]
