# Generated by Django 4.2.4 on 2023-09-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_imgforportfolio_img_linkforportfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkforportfolio',
            name='link_domain',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
