# Generated by Django 4.2.4 on 2023-09-20 16:50

import ckeditor.fields
from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_linkforportfolio_link_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('category', 'description'), required_languages=(), virtual_fields=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
