# Generated by Django 4.2.4 on 2023-09-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_me', '0002_contactme_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactme',
            name='phone_number',
            field=models.SmallIntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='contactme',
            name='seen',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
