# Generated by Django 4.2.4 on 2023-09-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_me', '0003_alter_contactme_phone_number_alter_contactme_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactme',
            name='phone_number',
            field=models.IntegerField(max_length=15),
        ),
    ]
