# Generated by Django 4.2.4 on 2023-09-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_me', '0004_alter_contactme_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactme',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
